services:
  bot:
    image: "${IMAGE_APP}"
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        UV_VERSION: $UV_VERSION
    restart: always
    env_file: .env
    command: >
      gunicorn --workers ${BOT_WORKERS:-1}
        --worker-class uvicorn.workers.UvicornWorker
        --bind :${BOT_PORT:-8001}
        --worker-tmp-dir ${BOT_WORKER_TMP_DIR:-/dev/shm}
        --timeout ${BOT_TIMEOUT:-60}
        --graceful-timeout ${BOT_GRACEFUL_TIMEOUT:-30}
        --keep-alive ${BOT_KEEP_ALIVE:-5}
        --access-logfile -
        --error-logfile -
        --forwarded-allow-ips='*'
        apps.bot.main:app
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    profiles:
      - "main"
    ports:
      - "${BOT_PUBLIC_PORT}:${BOT_PORT:-8001}"

  worker:
    image: "${IMAGE_APP}"
    env_file: .env
    restart: unless-stopped
    command: taskiq worker apps.worker.app:broker --no-configure-logging --log-level=${LOGGER_LEVEL:-INFO}
    # TODO: add healthcheck
    profiles:
      - "main"
    ulimits:
      nofile:
        soft: 4096
        hard: 4096

  worker-beat:
    image: "${IMAGE_APP}"
    env_file: .env
    restart: unless-stopped
    command: taskiq scheduler apps.worker.app:scheduler --no-configure-logging --skip-first-run --log-level=${LOGGER_LEVEL:-INFO}
    # TODO: add healthcheck
    profiles:
      - "main"
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
