[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning
    ignore::DeprecationWarning:fakeredis
    ignore:.*retry_on_timeout.*:DeprecationWarning
    ignore:.*lib_name.*:DeprecationWarning
    ignore:.*lib_version.*:DeprecationWarning