"""add_balance_to_users

Revision ID: 94eebc7de3b5
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 22:18:18.143405

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94eebc7de3b5"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("balance", sa.Numeric(precision=12, scale=2), server_default="10", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
