"""add_generated_cvs_table

Revision ID: b97b3c11fa81
Revises: eb3e64151167
Create Date: 2026-03-18 22:31:48.018523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b97b3c11fa81"
down_revision = "eb3e64151167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_cvs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("object_name", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=256), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_generated_cvs_job_id_jobs"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resume_id"], ["resumes.id"], name=op.f("fk_generated_cvs_resume_id_resumes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_generated_cvs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_cvs")),
    )
    op.create_index(op.f("ix_generated_cvs_job_id"), "generated_cvs", ["job_id"], unique=False)
    op.create_index(op.f("ix_generated_cvs_resume_id"), "generated_cvs", ["resume_id"], unique=False)
    op.create_index(op.f("ix_generated_cvs_user_id"), "generated_cvs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_cvs_user_id"), table_name="generated_cvs")
    op.drop_index(op.f("ix_generated_cvs_resume_id"), table_name="generated_cvs")
    op.drop_index(op.f("ix_generated_cvs_job_id"), table_name="generated_cvs")
    op.drop_table("generated_cvs")
    # ### end Alembic commands ###
