"""add_metadata_to_resumes

Revision ID: df5654cecf62
Revises: b2c3d4e5f6a7
Create Date: 2026-03-23 23:13:28.520265

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df5654cecf62"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None

_EMPTY_JSON = "{}"  # noqa: P103


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("metadata", sa.JSON(), server_default=_EMPTY_JSON, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "metadata")
    # ### end Alembic commands ###
